[package]
name = "fifteen2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
console = "0.15.8"
itertools = "0.12.1"
plotters = "0.3.5"
rand = "0.8.5"
